name: Syntelligence
favicon: null
layout_spectrum: 0.25248
typography_spectrum: 0.8723404
title: Syntelligence Coaching
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a0a4aa'
    - '#4c4f50'
    - '#61b419'
    - '#a8d868'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
