name: Syntelligence
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8723404
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Syntelligence Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a0a4aa'
    - '#4c4f50'
    - '#61b419'
    - '#a8d868'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
